a = User.create(username: 'Alex Haas', email: 'alexhaas@email.com', password: 'password')
b = User.create(username: 'Guest', email: 'guest@email.com', password: 'password')
c = User.create(username: 'Steve Holt', email: 'holt@email.com', password: 'password')
d = User.create(username: 'Michael Bluth', email: 'mbluth@email.com', password: 'password')
e = User.create(username: 'George Michael Bluth', email: 'gmbluth@email.com', password: 'password')
f = User.create(username: 'Tobias Fünke', email: 'analrapist@email.com', password: 'password')
g = User.create(username: 'Buster Bluth', email: 'babybuster@email.com', password: 'password')
h = User.create(username: 'Gob Bluth', email: 'gob@email.com', password: 'password')

g.songs.create(title: '2AM Club - Every Evening', upload_id: '24rnfjfr')
a.songs.create(title: 'Josh Cocktail - Fire', upload_id: '24rnfjfr')
b.songs.create(title: 'KiD CuDi - CudderIsBack', upload_id: '24rnfjfr')
g.songs.create(title: 'Hoodie Allen - No Interruption', upload_id: '24rnfjfr')
d.songs.create(title: 'Daddys Groove - Hurricane', upload_id: '24rnfjfr')
a.songs.create(title: 'DMB - Crash', upload_id: '24rnfjfr')
f.songs.create(title: 'Mike Posner - Still Not Over You', upload_id: '24rnfjfr')
e.songs.create(title: 'Cris Cab - In My Dreams', upload_id: '24rnfjfr')
g.songs.create(title: 'Big Sean - Too Fake', upload_id: '24rnfjfr')
b.songs.create(title: 'Jack Johnson - Holes to Heaven', upload_id: '24rnfjfr')
h.songs.create(title: 'The Fray - Over My Head', upload_id: '24rnfjfr')
e.songs.create(title: 'The Deans List - Dear Professor', upload_id: '24rnfjfr')
b.songs.create(title: 'Mike Posner - Wonderwall [cover]', upload_id: '24rnfjfr')
g.songs.create(title: 'Lil Wayne - Let the Beat Build', upload_id: '24rnfjfr')
f.songs.create(title: 'Empire on the Sun - Walking on a Dream', upload_id: '24rnfjfr')
e.songs.create(title: 'Atmosphere - Godlovesugly', upload_id: '24rnfjfr')
a.songs.create(title: 'Luke Bryan - Crash My Party', upload_id: '24rnfjfr')
c.songs.create(title: 'Wolfgang Gartner - Space Junk', upload_id: '24rnfjfr')
d.songs.create(title: 'Nosaj Thing - Aquarium', upload_id: '24rnfjfr')
h.songs.create(title: 'Chiddy Bang - Young Blood (Remix)', upload_id: '24rnfjfr')
c.songs.create(title: 'Nappy Roots - AwwNaw', upload_id: '24rnfjfr')
e.songs.create(title: 'Years & Years - Rear', upload_id: '24rnfjfr')
d.songs.create(title: 'Big Sean - Marvin & Chardonnay (feat. Kanye West)', upload_id: '24rnfjfr')
f.songs.create(title: 'The White Panda - Midnight Life', upload_id: '24rnfjfr')
a.songs.create(title: 'The Neighbourhood - Sweater Weather', upload_id: '24rnfjfr')
f.songs.create(title: 'B.o.B - Airplanes', upload_id: '24rnfjfr')
e.songs.create(title: 'Lady Antebellum - Compass', upload_id: '24rnfjfr')
a.songs.create(title: 'The Deans List - Caveman', upload_id: '24rnfjfr')
h.songs.create(title: 'Shwayze - Dont be Shy', upload_id: '24rnfjfr')



a.out_follows.create(followee_id: 2)
a.out_follows.create(followee_id: 4)
c.out_follows.create(followee_id: 1)
c.out_follows.create(followee_id: 2)
b.out_follows.create(followee_id: 4)
